# Generated by Django 5.1.1 on 2025-03-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('devil_fruit', models.CharField(blank=True, max_length=255, null=True)),
                ('last_bounty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debut_arc', models.CharField(blank=True, max_length=255, null=True)),
                ('haki', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('episode', models.CharField(blank=True, max_length=255, null=True)),
                ('debut_arc_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
